config/routes.rb
Rails.application.routes.draw do  

  resources :records

  resources :privacies

  resources :groups

  resources :friendships

  resources :applications

  resources :posts

  resources :categories

  resources :timelines

  resources :requests

  devise_for :users, :controllers => { registrations: 'registrations' }
  

  root 'applications#feed'
  
  get 'profile/:user_id', to: "users#profile" 
  get 'home', to: "applications#feed"
  post'/search', to: "users#search_user"
  get'/about', to: "users#about"

end

app/models/application.rb
class Application < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/privacy.rb
class Privacy < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @applications = Application.all
    respond_with(@applications)
  end

  def feed
    @records = Record.where(volunteer_id:current_user, status:false)
    @records.each do |record|
      @requests << Application.where(id:record.request_id).first
    end
    raw_posts=[]
    @friendships = Friendship.where(contact_id:current_user.id)
    @friendships.each do |friendship|
      @applications =[]
      @applications = Application.where(["volunteers_number = ? and applicant_id = ?", friendship.category, friendship.user_id])
      @applications.each do |application|
        @record = Record.where(volunteer_id:current_user.id)
        if !@record.blank?
          raw_posts << application
        end
        
      end
    end

    @posts = []
    raw_posts.each do |post|
      post_and_user_and_category = {post:post, user: User.find(post.applicant_id),category:Category.find(post.category_id)}
      @posts << post_and_user_and_category
    end
    
  end

  def show
    respond_with(@application)
  end

  def new
    @application = Application.new
    respond_with(@application)
  end

  def edit
  end

  def create
    @application = Application.new(application_params)    

    respond_to do |format|
      if @application.save
        format.json { render json: @application, status: :ok }
        Privacy.create(request_id: @application.id, group_id: @application.group_id)
      else
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end 
  end

  def update
    @application.update(application_params)
    respond_with(@application)
  end

  def destroy
    @application.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end 

  private
    def set_application
      @application = Application.find(params[:id])
    end

    def application_params
      params.require(:application).permit(:applicant_id, :title, :description, :category_id, :request_date, :status, :volunteers_number, :group_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:applicant_id, :title, :description, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index		
	end
	def search_user
		@first_name = params[:first_name]
		@last_name = params[:last_name]
		@relevant_results = User.all.where("first_name like ? AND last_name like?", "%#{@first_name}%", "%#{@last_name}%")
	end

	def profile				
		@user = User.where(id:params[:user_id]).first	
		
				
		raw_groups = Group.where(user_id:current_user.id)

		if raw_groups.blank?
			Group.create(name: 'Acquaintances', user_id: current_user.id)
		end
		@groups = []

		raw_groups.each do |group|
			contacts=[]
			@relations = Friendship.where(user_id:@user.id, category:group.id)
			@relations += Friendship.where(contact_id:@user.id, category:group.id)
			@relations.each do |relation|
				contacts << User.where(id:relation.contact_id).first
			end
			group_and_contacts = {group:group, contacts:contacts}
			@groups << group_and_contacts
		end
		@user_groups=[]
		@user_groups = Group.where(user_id:current_user.id)

		Group.where(user_id: @user.id)

		raw_posts = Application.where(applicant_id:@user.id, group_id:).order("created_at DESC")
		@posts = []

		raw_posts.each do |post|
			post_and_category = {post:post, category:Category.find(post.category_id)}
			@posts << post_and_category
		end
	end
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :gender, :birthdate, :encrypted_password, :points)
	end
	def new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/privacies_helper.rb
module PrivaciesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :applicant_id %><br>
    <%= f.number_field :applicant_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :request_date %><br>
    <%= f.date_select :request_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :volunteers_number %><br>
    <%= f.number_field :volunteers_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/feed.html.erb
<div class="row clearfix">
	<div class="col-md-12 column">				
		<nav class="navbar navbar-default header navbar-fixed-top" role="navigation">
			<div class="navbar-header">
				 <a class="navbar-brand" href="#"><span class="fontChange">Goodwill</span></a>
			</div>				
			<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-left">
	          <li>
	          	<br>
	           <%= form_tag("/search", method: "post", class: 'form-inline') do %>				  <div class="form-group">
				  <%= text_field_tag('first_name', nil, placeholder: 'first name', class: 'form-control' ) %>
				  </div>
				  <div class="form-group">
				  <%= text_field_tag('last_name', nil, placeholder: 'last name', class: 'form-control') %>
				  </div>
				  <div class="form-group">
				  <%= submit_tag("Search", class: 'btn btn-default') %>
				</div>
				<% end %>
	            
	          </li>           
	        </ul>
			<ul class="nav nav-pills navbar-left" style="padding:10px;">					
					<li class="active" style="margin-left:100px;">
						<a href="/home">Home</a>
					</li>
					<li class="active" style="margin-left:20px;">
						<a href="/profile/<%= current_user.id %>">Profile</a>
					</li>		
									
					<li class="active" style="margin-left:20px;">
						<a href="/about">About</a>
					</li>					
				</ul>
			<ul class="nav navbar-nav navbar-right">
					<li><br><%= "Welcome " + current_user.first_name + " " +current_user.last_name %></li>
			  <li>
			  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
			  </li>
			</ul>				
			</div>				
		</nav>
	</div>
</div>
<div class="space"></div>

<div class="row clearfix">
	<div class="col-md-4 column">	
		<div class="row clearfix ">	
			<div class="col-md-12 column">	
				<%= image_tag "profile.png", width:"290px", height:"300px", style: "padding:45px;" %>

				
			</div>
		</div>

		<div class="row clearfix">
			<div class="column col-md-12">
				<h2 id="" class="page-header">Notifications</h2>
				<% @posts.each do |post| %>
		<div class="media post" style="margin-right:100px;">			
			<div class="media-body">
				<h4 class="media-heading">
					<b class="gray"><%= post[:user].first_name  %></b><small> Asked to help you with </small> <b class="gray"><%= post[:category].name %></b>

					

				</h4> <p class="gray"><cite><%= post[:post].description  %></cite></p>
				<em class="gray"><%= post[:post].updated_at %></em>
				<hr>
			</div>
		
		</div>
		
		<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-8 column postlist">
		<div class="col-md-12 column"  id="profile-top">	
		<h2 id="profile-title" class="page-header"><%= "#{current_user.first_name} #{current_user.last_name}"  %></h2>

	</div>
	
		
		<% @posts.each do |post| %>
		<div class="media post form-div">
			<a href="#" class="pull-left"><%= image_tag "profile.png", width:"100px", height:"100px", class:"media-object" %></a>
			<div class="media-body">
				<h4 class="media-heading">
					<b class="gray"><%= post[:user].first_name  %></b><small> needs some help with </small> <b class="gray"><%= post[:category].name %></b>

					

				</h4> <p class="gray"><cite><%= post[:post].description  %></cite></p>
				<em class="gray"><%= post[:post].updated_at %></em>

			</div>
			<%= form_for(Record.new, class: 'form-inline', remote: true) do |f| %>				 
			  <%= f.hidden_field :request_id, :value => post[:post].id %>
			  <%= f.hidden_field :applicant_id, :value => post[:post].applicant_id %>
			  <%= f.hidden_field :volunteer_id, :value => current_user.id %>			  
			  <div class="form-group">
			    <%= f.submit "volunteer", class: 'btn btn-default pull-right' %>
			  </div>			  
			<% end %>
		</div>
		
		<% end %>
	</div>
</div>

</div>

<script type="text/javascript">
	/*var postCount = $(".post").length;*/

	$('textarea.expand').focus(function () {
	    $(this).animate({ height: "10em" }, 500);
	});

	/*setInterval(function(){
		$.ajax({
		type: "GET",
		url: "/posts/checkForNewsPosts"
		}).done(function(response) {
			if(parseInt(response) > postsCount){
				alert("Refresh, there are new posts!");
			}
		});
	}, 10000);*/
</script>
</div>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>Request date</th>
      <th>Status</th>
      <th>Volunteers number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.applicant_id %></td>
        <td><%= application.title %></td>
        <td><%= application.description %></td>
        <td><%= application.category_id %></td>
        <td><%= application.request_date %></td>
        <td><%= application.status %></td>
        <td><%= application.volunteers_number %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applicant:</strong>
  <%= @application.applicant_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @application.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @application.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @application.category_id %>
</p>

<p>
  <strong>Request date:</strong>
  <%= @application.request_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application.status %>
</p>

<p>
  <strong>Volunteers number:</strong>
  <%= @application.volunteers_number %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>