config/routes.rb
Rails.application.routes.draw do  

  resources :records

  resources :privacies

  resources :groups

  resources :friendships

  resources :applications

  resources :posts

  resources :categories

  resources :timelines

  resources :requests

  devise_for :users, :controllers => { registrations: 'registrations' }
  

  root 'applications#feed'
  
  get 'profile/:user_id', to: "users#profile" 
  get 'home', to: "applications#feed"
  post'/search', to: "users#search_user"
  get'/about', to: "users#about"

end

app/models/application.rb
class Application < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/privacy.rb
class Privacy < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @friendships = Friendship.all
    respond_with(@friendships)
  end

  def show
    respond_with(@friendship)
  end

  def new
    @friendship = Friendship.new
    respond_with(@friendship)
  end

  def edit
  end

  def create
    @friendship = Friendship.new(friendship_params)
    respond_to do |format|
      if @friendship.save
        format.json { render json: @friendship, status: :ok }
      else
        format.json { render json: @friendship, status: :unprocessable_entity }
      end
    end 
  end

  def update
    @friendship.update(friendship_params)
    respond_with(@friendship)
  end

  def destroy
    @friendship.destroy
    respond_with(@friendship)
  end

  private
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    def friendship_params
      params.require(:friendship).permit(:user_id, :contact_id, :category)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:applicant_id, :title, :description, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/privacies_helper.rb
module PrivaciesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.number_field :contact_id %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.number_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Contact</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.contact_id %></td>
        <td><%= friendship.category %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @friendship.contact_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @friendship.category %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>